---
title: "P8105 DS Final Project fall 2019"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Welcome

This website is built for data science final project, where we analyze the dataset based on the police report (MV104-AN) and the records of Motor Vehicle Collision have been modified daily according to NYPD since May, 7th, 2014.

### About

The dataset is generated based on the police report (MV104-AN) and the records of Motor Vehicle Collision have been modified daily according to NYPD since May, 7th, 2014. The “Collision” here includes the situation where someone is injured or killed, or where there is at least $1000 worth of damage. The density of vehicles in NYC is larger compared to other cities in the US and the safety of motor vehicle driving becomes one of the most important topics for NYC citizens. Therefore, we would like to reveal the distribution of motor vehicle accidents in NYC located in different areas and use the factor CONTRIBUTING FACTOR 1 to 5 to predict the number of passing-bys that would be killed or injured.

**data source**: [NYPD Motor Vehicle Collisions dataset from NYC OpenData website](https://data.cityofnewyork.us/Public-Safety/NYPD-Motor-Vehicle-Collisions-Crashes/h9gi-nx95 )

### Group member

Weiwei Qi: wq2151; Qimin Zhang: qz2392; Junxian Chen: jc5314; Xinyu Shen: xs2384; Bingkun Luo: bl2789. 



### Contact Information

Weiwei Qi

New York, New York 10032  

Email: [wq2151@cumc.columbia.edu](mailto:wq2151@cumc.columbia.edu)

Phone: 646-683-6801