---
title: "Project Report"
author: "Bingkun Luo, Junxian Chen, Qimin Zhang, Weiwei Qi, Xinyu Shen"
date: "2019/11/23"
output:
    html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  message = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_gray(base_size = 10) + theme(legend.position = "bottom"))
```


```{r, include=FALSE}
drug_df = 
  read_csv("./data/Accidental_Drug_Related_Deaths_2012-2018.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  separate(year, into = c("year", "del", "del_"), sep = " ") %>% 
  select(-del, -del_) %>% 
  separate(injury_city_geo, into = c("injury_city", "injury_geo"), sep = "CT") %>% 
  separate(injury_geo, into = c("inj_lat", "inj_long"), sep = ",") %>% 
  mutate(
    inj_lat = as.numeric(str_remove(inj_lat, "\\(")),
    inj_long = as.numeric(str_remove(inj_long, "\\)")),
    injury_city = str_remove(injury_city, "\\,")
  ) %>% 
  select(-date_type) %>% 
  pivot_longer(
    heroin:any_opioid,
    names_to = "drug_name",
    values_to = "drug_use") %>%  
  drop_na(drug_use) %>%
  #all opiates are opioids, not all opioids are opiates.
  mutate(
    date_in_month = zoo::as.yearmon(paste(year, month, sep = "-"), "%Y-%m"),
    date = as.Date(with(., paste(year, month, day, sep = "-")), "%Y-%m-%d"),
    drug_name = case_when(drug_name == "any_opioid" ~ "opioid",
                          drug_name == "opiate_nos" ~ "opioid",
                          drug_name == "fentanyl_analogue" ~ "fentanyl",
                          TRUE ~ as.character(drug_name)),
    drug_type = case_when(drug_name == "heroin" ~ "Natural drugs",
                          drug_name == "cocaine" ~ "Natural drugs",
                          drug_name == "morphine_not_heroin" ~ "Natural drugs",
                          drug_name == "ethanol" ~ "Alcohol",
                          drug_name == "hydrocodone" ~ "POM",
                          drug_name == "oxymorphone" ~ "POM",
                          drug_name == "hydromorphone" ~ "POM",
                          drug_name == "amphet" ~ "POM",
                          drug_name == "tramad" ~ "POM",
                          drug_name == "methadone" ~ "POM",
                          drug_name == "oxycodone" ~ "POM",
                          drug_name == "benzodiazepine" ~ "POM",
                          drug_name == "opioid" ~ "POM",
                          drug_name == "fentanyl" ~ "POM",
                          TRUE ~ as.character(drug_name)),
    drug_name = as.factor(drug_name),
    drug_type = as.factor(drug_type)
  )
```


## 1. Bar plot: count vs age group with race group

```{r}
drug_df = 
  drug_df %>% 
  .[!is.na(drug_df$race), ] 

drug_df %>% 
  .[!is.na(drug_df$age), ] %>%  
  mutate(
  age_group = ifelse(
    age < 18, "<18", ifelse(
      age < 30 & age >= 18, "18~30", ifelse(
        age < 40 & age >= 30, "30~40", ifelse(
          age < 50 & age >= 40, "40~50", ifelse(
            age < 60 & age >= 50, "50~60", ifelse(
              age < 70 & age >= 60, "60~70", "70+"))))))) %>% 
  mutate(age_group = as.factor(age_group)) %>% 
  ggplot(aes(x = age_group, fill = race)) + 
  geom_histogram(stat = "count", width = 0.6) + 
  labs(
    title = "Age group vs Death count", 
    x = "Age group", 
    y = "Death count due to drugs") + 
  theme_bw() + 
  theme(
    plot.title = element_text(hjust = 0.5), 
    legend.position = "bottom",
    legend.text = element_text(size = 8)) + 
  guides(col = guide_legend(nrow = 2))
```


## 2. Volin plot: Gender difference in drug-related deaths {.tabset}

```{r include=FALSE}
voline_plot = 
  drug_df %>%
  group_by(drug_name) %>%
  mutate(count = n()) %>%
  select(age, race, sex, drug_name, count, drug_type) %>%
  drop_na() %>%
  arrange(desc(count))
```

### Top 3 Fatalized Drug

```{r echo=FALSE, warning=FALSE}
voline_plot %>%
  filter(drug_name == "fentanyl" | drug_name == "opioid" | drug_name == "heroin") %>%
  arrange(count) %>%
  plot_ly(type = 'violin', orientation = "h") %>%
  add_trace(
    y = ~drug_name[voline_plot$sex == 'Male'], x = ~age[voline_plot$sex == 'Male'],
    legendgroup = 'Male', scalegroup = 'Male', name = 'Male',
    side = 'negative',
    box = list(visible = T),
    meanline = list(visible = T),
    line = list(color = '')) %>%
  add_trace(
      y = ~drug_name[voline_plot$sex == 'Female'], x = ~age[voline_plot$sex == 'Female'],
      legendgroup = 'Female', scalegroup = 'Female', name = 'Female',
      side = 'positive',
      box = list(visible = T),
      meanline = list(visible = T),
      line = list(color = ''),
      marker = list(
        line = list(
          width = 2,
          color = ""
        ))) %>% 
  layout(
    xaxis = list(title = "Distribution among Ages"),
    yaxis = list(title = "Use of Drug", zeroline = F),
    violingap = 0.5,
    violingroupgap = 0,
    violinmode = 'overlay',
    colorway = c('#cd7eaf','blue')
  )
```

### Major Source of Drug

```{r echo=FALSE, warning=FALSE}
voline_plot %>%
  plot_ly(type = 'violin') %>%
  add_trace(
    x = ~drug_type[voline_plot$sex == 'Male'], y = ~age[voline_plot$sex == 'Male'],
    legendgroup = 'Male', scalegroup = 'Male', name = 'Male',
    side = 'negative',
    box = list(visible = F),
    meanline = list(visible = T,color = 'black'),
    line = list(color = '')) %>%
  add_trace(
    x = ~drug_type[voline_plot$sex == 'Female'], y = ~age[voline_plot$sex == 'Female'],
    legendgroup = 'Female', scalegroup = 'Female', name = 'Female',
    side = 'positive',
    box = list(visible = F),
    meanline = list(visible = T,color = "red"),
    line = list(color = ''),
    marker = list(
        line = list(
          width = 2,
          color = ""
    ))) %>% 
  layout(
    xaxis = list(title = "Types of Drug "),
    yaxis = list(title = "Distribution among Ages ", zeroline = F),
    violingap = 0.5,
    violingroupgap = 0,
    violinmode = 'overlay',
    colorway = c('#cd7eaf','blue')
    )
```

### All Types of Drug

```{r echo=TRUE, warning=FALSE}
voline_plot %>%
  plot_ly(type = 'violin') %>%
  add_trace(
    x = ~drug_name[voline_plot$sex == 'Male'], y = ~age[voline_plot$sex == 'Male'],
    legendgroup = 'Male', scalegroup = 'Male', name = 'Male',
    side = 'negative',
    box = list(visible = T),
    meanline = list(visible = T),
    line = list(color = ''),
    marker = list(line = list(width = 2,color = "purple"))) %>%
  add_trace(
    x = ~drug_name[voline_plot$sex == 'Female'], y = ~age[voline_plot$sex == 'Female'],
    legendgroup = 'Female', scalegroup = 'Female', name = 'Female',
    side = 'positive',
    box = list(visible = T),
    meanline = list(visible = T),
    line = list(color = ''),
    marker = list(line = list(width = 2,color = ""))) %>% 
  layout(
    xaxis = list(title = "Use of Drug ",rangeslider = list(type = "drug_name")),
    yaxis = list(title = "Distribution among Ages ", zeroline = F),
    violingap = 0.5,
    violingroupgap = 0,
    violinmode = 'overlay',
    colorway = c('#cd7eaf','blue')
    )
```


## 3. Spaghetti plot: no. of death vs. time (group by types of drug)

```{r}
spaghetti_plot1 = 
  drug_df %>% 
  drop_na(date_in_month) %>% 
  arrange(date_in_month) %>% 
  group_by(date_in_month, drug_type) %>% 
  count() %>% 
  ggplot(aes(x = date_in_month, y = n, color = drug_type)) +
  geom_line() +
  xlab("Date") +
  ylab("Number of death") +
  facet_grid(~drug_type)

spaghetti_plot1
```


```{r}
spaghetti_plot2 = 
  drug_df %>% 
  drop_na(date_in_month) %>% 
  arrange(date_in_month) %>% 
  group_by(date_in_month, drug_name) %>% 
  count() %>% 
  ggplot(aes(x = date_in_month, y = n, color = drug_name)) +
  geom_line() +
  xlab("Date") +
  ylab("Number of death") 

ggplotly(spaghetti_plot2)
```


```{r}
n_plot = 
  drug_df %>% 
  drop_na(date) %>% 
  arrange(date) %>% 
  group_by(date, drug_type, year, month) %>% 
  count() 

map = 
  ggplot(n_plot ,aes(x = month, y = year)) + 
  geom_point(aes(color = drug_type, size = n), alpha = 0.2) +
  scale_color_manual(values = c("yellow",'#cd7eaf','green','#f3cec9')) +
  scale_size(range = c(2, 12)) +
  theme_light() +
  xlab("Month") +
  ylab("Year")

ggplotly(map)
```


```{r}
line = 
  ggplot(n_plot,aes(x = date, y = drug_type)) + 
  geom_point(aes(color = drug_type, size = n), alpha = 0.5) +
  scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07","yellow")) +
  scale_size(range = c(0.5, 12))

ggplotly(line)
```


## 4. Heat map showing the number of death in each drug type across the year

```{r}
drug_df %>% 
  drop_na(date) %>% 
  arrange(date) %>% 
  group_by(date, drug_type) %>% 
  count() %>% 
  ggplot(aes(x = drug_type, y = date)) +
  geom_bin2d() +
  scale_fill_gradient(low = "white", high = "steelblue") +
  xlab("Date") +
  ylab("Number of death") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10), panel.background = element_blank()) 
``` 

```{r}
drug_df %>% 
  drop_na(date) %>% 
  arrange(date) %>% 
  group_by(date, drug_name) %>% 
  count() %>% 
  ggplot(aes(x = drug_name, y = date)) +
  geom_bin2d() +
  scale_fill_gradient(low = "white", high = "steelblue") +
  xlab("Date") +
  ylab("Number of death") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10), panel.background = element_blank()) 
``` 





