---
title: "P8105 Final Project Proposal"
date: "11/6/2019"
output: github_document
---

### The group members (names and UNIs)

Weiwei Qi: wq2151; Qimin Zhang: qz2392; Junxian Chen: jc5314; Xinyu Shen: xs2384; Bingkun Luo: bl2789.

### The tentative project title

Analyses in drug use and related death in Connecticut

### The motivation for this project

Illicit drug use in the United States has been increasing and the number of related death is also growing. Therefore, studying the relationship between drug use and related death is important to discourage drug use and prevent death. In this project, we are going to analyze the data in drug use and related death in  Connecticut from 2012 to 2018 and intend to discover some critical factors in drug use that will arise high chance to be dead.

### The intended final products



### The anticipated data sources

Accidental Drug Related Deaths 2012-2018  from DATA.GOV which contains lists of each accidental death associated with drug overdose in Connecticut from 2012 to 2018. (https://catalog.data.gov/dataset/accidental-drug-related-deaths-january-2012-sept-2015)

### The planned analyses / visualizations / coding challenges

**Planned analyses:** Analyze the associations between race, gender, age, drug use and related death.  Try to find out important factor that will reduce death in drug use. Build regression model.

**Planned visualizations:** 

(1) Dates versus uumber of drug use related death to see the pattern of death over different time (e.x. any seasonal trend)

(2) Heat map showing distribution of death location

(3) Distribution of race, gender, and sex in drug use and related death

(4) Number of death for each kinds of drug

(4) Shiny plots.

**Challenges:** 

### The planned timeline

* Nov.7 - Nov. 14: Tidy the dataset, start doing the planned analyses.

* Nov.14 - Nov. 21: Keep working on the analyses and start doing planned visualizations using the obtained results.

* Nov.21 - Nov.28: Start making the website and writing the report.

* Nov.28 - Dce.5: Finalize the report/website, finish making the screencast.

* Dec. 5: Submission of the report/website/screencast.

